PKG_NAME="onkyo-eiscp"
PKG_VERSION="1.2.7"
PKG_ARCH="any"
PKG_LICENSE="OSS"
PKG_SITE="http://pypi.org/project/onkyo-eiscp/"
PKG_URL="http://pypi.python.org/packages/source/o/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.gz"
PKG_DEPENDS_TARGET="toolchain Python"
PKG_SECTION="python/system"
PKG_SHORTDESC="This is a Python library to control and interact with Onkyo receivers over the network."
PKG_LONGDESC="This is a Python library to control and interact with Onkyo receivers over the network. It is also a ready-made command line script you can use without knowing how to program. Finally, this repository contains a YAML file containing all the commands defined by the Onkyo protocol, automatically generated by parsing the official documentation."

PKG_IS_ADDON="no"
PKG_AUTORECONF="no"

pre_make_target() {
  strip_lto
  export PYTHONXCPREFIX="$SYSROOT_PREFIX/usr"
}

make_target() {
  python setup.py build --cross-compile
}

makeinstall_target() {
  python setup.py install --root=$INSTALL --prefix=/usr
}

post_makeinstall_target() {
  find $INSTALL/usr/lib -name "*.py" -exec rm -rf "{}" ";"
  rm -rf $INSTALL/usr/lib/python*/site-packages/*/tests
}
